#!/bin/bash
#This script run every 5 seconds

while (sleep 5 && [ /tmp/.lastupdate -nt /etc/owping/lastupdated.txt ] || ( tk=$(cat "/etc/owping/tk.txt") ; wait $! ; date=$(cat "/etc/owping/$tk/outDate.txt" ) ; time=$(cat "/etc/owping/$tk/outTime.txt") ; opt=$(cat "/etc/owping/$tk/outOpt.txt") ;  opts="$tk -d $date -t $time -x $opt"; /etc/owping/owplot.sh $opts >> /etc/owping/$tk/plot.log ; touch /tmp/.lastupdate )) & 
do
    wait $!
done
